#include "/Engine/Public/Platform.ush"

float4 MainColor;
Texture2D MainTexture;
SamplerState MainTextureSampler;

void MainVS(
    in float4 InPosition : ATTRIBUTE0,
    in float2 InUV : ATTRIBUTE1,
    out float2 OutUV : TEXCOORD0,
    out float4 OutPosition : SV_POSITION
)
{
    OutPosition = InPosition;
    OutUV = InUV;
}

void MainPS(
    in float2 UV : TEXCOORD0,
    out float4 OutColor : SV_Target0
)
{
    OutColor = MainColor * MainTexture.Sample(MainTextureSampler, UV.xy);
}